#!/bin/bash


### Variables ###
RSYNC_FLAGS="-az --delete"          # Flags used with rsync (archive/recursive, compress)

RDOUT_DIR="rdout/"                  # Directory to be copied to readouts
SYNC_DIR="sync/"                    # Directory to be copied to syncboards

RDOUT_IP_FILE="etc/rdout_ips.txt"   # File containing IP's for the readout Pis
SYNC_IP_FILE="etc/sync_ips.txt"     # File containing IP's for the syncboard Pis

REMOTE_USR="pi"                     # The username for the remote Pis to be connected to
REMOTE_RDOUT_DIR="~/rdout/"         # Desired path on the remote rdout Pis
REMOTE_SYNC_DIR="~/sync/"           # Desired path on the remote sync Pis


### Read Files ###
while read -r IP # Reads a file (specified in the done < FILE line) line by line into the variable IP
do
    echo "Copying $RDOUT_DIR to $IP:$REMOTE_RDOUT_DIR"
    rsync $RSYNC_FLAGS $RDOUT_DIR $REMOTE_USR@$IP:$REMOTE_RDOUT_DIR >> /dev/null

    # If something goes wrong, let the user know and exit
    if [ $? -ne 0 ]
    then
        echo "rsync with" $IP "failed. Aborting."
        exit 1
    fi
done < $RDOUT_IP_FILE

while read -r IP
do
    echo "Copying $SYNC_DIR to $IP:$REMOTE_SYNC_DIR"
    rsync $RSYNC_FLAGS $SYNC_DIR $REMOTE_USR@$IP:$REMOTE_SYNC_DIR >> /dev/null

    if [ $? -ne 0 ]
    then
        echo "rsync with" $IP "failed. Aborting"
        exit 1
    fi
done < $SYNC_IP_FILE
