#!/bin/bash
# not really, but just want the syntax highlighting


# TODO
#   Test DAQ w/ real hexaboards
#   Verify CRC in DAQ
#   Organize rdout/ directory
#   Organize sync/ directory
#   Finalize master run scripts to the rdout/ and sync/ directories for the Pis to run
#   Use pgrep to find sync and rdout processes to be able to kill them
#   Update master run script with this information
