#!/bin/bash
# not really, but just want the syntax highlighting


# TODO
#   Test DAQ w/ real hexaboards
#   Verify CRC in DAQ
#   Fill and organize rdout/ directory
#   Fill and organize sync/ directory
#   Add master run scripts to the rdout/ and sync/ directories for the Pis to run
#   Figure out how to run the ssh commands remotely and then kill them when done
#   Update master run script with this information
