#!/bin/bash
# not really, but just want the syntax highlighting


# TODO
#   Test DAQ w/ real hexaboards
#   Verify CRC in DAQ
#   Organize rdout/ directory
#   Organize sync/ directory
#   Make common directory for files in both rdout and sync
#   Clean up new_rdout.c from the changes made for the stop.run.please method to work
#   Finalize master run scripts to the rdout/ and sync/ directories for the Pis to run
#   Finalize main master script
