#!/bin/bash



#################### Arguments ####################
if [ $# -ne 1 ]
then
    echo "Incorrect arguments. Should be [PEDESTAL]"
    exit 1
fi
PED=$1



#################### Variables ####################
SYNC_NAME="sync_debug"

# Directories
SYNCDIR="$PWD"
BINDIR="$SYNCDIR/bin"
SRCDIR="$SYNCDIR/src"
FWDIR="$SYNCDIR/fw"

# Executables
PROGEXE="$BINDIR/ProgramFPGA"
SYNCEXE="$BINDIR/$SYNC_NAME"
TRIGEXE="$BINDIR/enable_triggers"
TRIGSTATUS="$BINDIR/get_trigger_enabled"
COMPILE="$SYNCDIR/compile"

# Firmware Files
SYNC_FW="$FWDIR/sync_orm1.hex"
CTL_FW="$FWDIR/ctl1.hex"

# ORMs
SYNC_ORM=4
CTL_ORM=4

# Other
SYNC_ARGS="$PED"
END_FILE="$SYNCDIR/stop.run.please"



#################### STARTUP ####################
# Remove end file so the helper process will run
if [ -f $END_FILE ]
then
    rm $END_FILE
fi

# Kill any old sync processes
TMP="$(pgrep $SYNC_NAME)"
if [ $TMP ]
then
    sudo kill $TMP
fi




#################### FW INSTALL ####################
# Sync ORM
echo "sudo $PROGEXE $SYNC_ORM < $SYNC_FW"
# TODO CHECK SUCCESS



#################### RUN SYNC ####################
# Compile (using the compile script)
$COMPILE
# TODO CHECK SUCCESS

# Run
nohup sudo $SYNCEXE $SYNC_ARGS &> log.txt &
