#!/bin/bash



#################### Arguments ####################
if [ $# -ne 3 ]
then
    printf "Incorrect arguments. Should be [PEDESTAL] [IPBUS IP] [IPBUS MAC]\n"
    exit 1
fi
PED=$1
IP=$2
MAC=$3



#################### Variables ####################
RDOUT_NAME="rdout_helper"

# Directories
RDOUTDIR="$PWD"
BINDIR="$RDOUTDIR/bin"
SRCDIR="$RDOUTDIR/src"
FWDIR="$RDOUTDIR/fw"

# Executables
PROGEXE="$BINDIR/ProgramFPGA"
RDOUTEXE="$BINDIR/$RDOUT_NAME"
SLEEPEXE="$BINDIR/take_a_nap"
PWREXE="$BINDIR/pwr_cycle_fpgas"
COMPILE="$RDOUTDIR/compile"
IPEXE="$BINDIR/set_ip_mac_address"

# Firmware Files
DATA_FW="$FWDIR/data_orm_dly.hex"           # DDR
CTL_FW="$FWDIR/ctl_orm_dly.hex"             # DDR
#DATA_FW="$FWDIR/non_ddr/data_orm1.hex"     # NON DDR
#CTL_FW="$FWDIR/non_ddr/ctl_orm_rst.hex"    # NON DDR

# ORM Arrays
DATA_ORMS=( 0 1 2 3 )
CTL_ORM=4

# Other
RDOUT_ARGS="$PED"
END_FILE="$RDOUTDIR/stop.run.please"
IP_ARGS="$IP $MAC"
LOGFILE="$RDOUTDIR/rdout.log"



#################### STARTUP ####################
# Remove end file so the helper process will run
if [ -f $END_FILE ]
then
    rm $END_FILE
fi

# Kill any old rdout processes
TMP="$(pgrep $RDOUT_NAME)"
if [ $TMP ]
then
    sudo kill $TMP
fi

# Clean up the log file
echo "" > $LOGFILE



#################### FW INSTALL ####################
# Data ORMs
for ORM in "${DATA_ORMS[@]}"
do
    printf "\tProgramming DATA ORM $ORM\n"
    sudo $PROGEXE $ORM < $DATA_FW >> $LOGFILE
    # TODO CHECK SUCCESS
done

# CTL ORM
printf "\tProgramming CTL ORM\n"
sudo $PROGEXE $CTL_ORM < $CTL_FW >> $LOGFILE
# TODO CHECK SUCCESS



#################### COMPILE ####################
# Compile (using the compile script)
$COMPILE >> $LOGFILE
# TODO CHECK SUCCESS



#################### SET IP & MAC ####################
printf "\tSetting IP and MAC addresses\n"
sudo $IPEXE $IP_ARGS >> $LOGFILE



#################### RUN RDOUT HELPER ####################
# Run
nohup sudo $RDOUTEXE $RDOUT_ARGS &> $LOGFILE &
